### ISSUE TITLE
Update list of GitHub topic associated with the project

### ISSUE THREAD

**Issue by jcfr** [c0un7-z3r0/CubeAnet#1]
To help prospective users, I suggest to remove the `3d-slicer` GitHub topic and instead use `slic3r`.

Indeed, assuming you intended to reference `Slic3r` and not `3D Slicer`, this change would make sense.

| Name | URL | GitHub topic | GitHub Project |
|--|--|--|--|
| Slic3r | https://slic3r.org/ | [slic3r](https://github.com/topics/slic3r) | https://github.com/slic3r/Slic3r |
| 3D Slicer | https://slicer.org | [3d-slicer](https://github.com/topics/3d-slicer) | https://github.com/Slicer/Slicer |

### Screenshots

2022.01.25:

![image](https://user-images.githubusercontent.com/219043/151232770-d5109190-8773-4611-a7ef-52d5c848cc6a.png)

**Comment by c0un7-z3r0** [comment]
My bad. Thanks for letting me know. 👍 I removed it.
